prefix = "./search"
stop-words = "stopwords.txt"

dataset = 'week9 submitted quiz questions'
corpus = "line.toml"
index = 'idx-week9 submitted quiz questions'

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
